// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUxvYw2PbN0Jqgmp8ltH7fbi2lpHR0Qko',
    appId: '1:898746990545:web:5b8e90eee26c2a683eeaf0',
    messagingSenderId: '898746990545',
    projectId: 'letsjam-c4ee3',
    authDomain: 'letsjam-c4ee3.firebaseapp.com',
    storageBucket: 'letsjam-c4ee3.appspot.com',
    measurementId: 'G-SZX0S20PJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_flnPUA2GZoAPbhUPGpPnVXoYsEY_yIs',
    appId: '1:898746990545:android:82fc2a2606c9afcd3eeaf0',
    messagingSenderId: '898746990545',
    projectId: 'letsjam-c4ee3',
    storageBucket: 'letsjam-c4ee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS-DeZfpA0spP0wbe2GCPIMtMYwF2gpCk',
    appId: '1:898746990545:ios:e6230f571deed1513eeaf0',
    messagingSenderId: '898746990545',
    projectId: 'letsjam-c4ee3',
    storageBucket: 'letsjam-c4ee3.appspot.com',
    androidClientId: '898746990545-85ugnf7itbbmj72p02nt7bg6athf6ndv.apps.googleusercontent.com',
    iosClientId: '898746990545-c4en4f0oaomm4c451s87n49ksm4bkj2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.pbl',
  );
}
